### ISSUE TITLE
A project name collision

### ISSUE THREAD

**Issue by sskras** [tycho/cpuid#29]
Last week I used you project as an alternative to the CPUID functionality included into AIDA64.

Today I learned that there two different projects using the same name, another one being https://www.etallen.com/cpuid.html (under the GPL v2).

Now as it was born some years earlier:
```
Mon Feb  6 2006 Todd Allen <todd.allen@etallen.com>
	* Initial public release.
```

... and is included into at least Debian (IIRC), I guess something need to be done about the situation. 
I doubt both project will merge.  I think it would be nice to adjust name of the newer project, this repo.

At least this project seems to be cross-platform, so maybe it could be renamed into `cross-cpuid`, `cpuid-new` or something alike?

**Comment by tycho** [comment]
I'm not really interested in the name collision because it's just named after the Intel CPUID instruction, just as Todd Allen's version is.
