### ISSUE TITLE
Please add TSC non-stop

### ISSUE THREAD

**Issue by sitsofe** [tycho/cpuid#5]
Is it possible to output whether the CPU supports TSC non-stop (see http://oliveryang.net/2015/09/pitfalls-of-TSC-usage/#311-cpu-tsc-capabilities )?

**Comment by sitsofe** [comment]
(I should note the Linux kernel carries a list of mappings (e.g. see http://elixir.free-electrons.com/linux/latest/source/arch/x86/include/asm/cpufeatures.h#L102 ).

**Comment by tycho** [comment]
It already does:

https://github.com/tycho/cpuid/blob/master/feature.c#L512

**Comment by sitsofe** [comment]
Isn't that something different? I thought there were two types of TSC invariant:

CPU has a constant rate of ticking regardless of frequency
CPU has a non-stop rate of ticking regardless of CPU power saving

Are you multiplexing the two together like Linux to create a synthetic "truly invariant attribute" or is it the case only one is being picked (e.g. CONSTANT_TSC)?

**Comment by sitsofe** [comment]
I stand corrected - it is NONSTOP_TSC that appears to be synthetic - http://elixir.free-electrons.com/linux/latest/source/arch/x86/kernel/cpu/intel.c#L160 .

**Comment by tycho** [comment]
Yeah, the Linux kernel developers had some funny ways of figuring out whether or not they could depend on the TSC before the feature bit was available.

**Comment by iSamF** [comment]
Sorry guys - I just logged into GitHub after a long hiatus, since I don't work at the company that was paying me to support SAMTOOL any longer!  I don't plan on keeping the tool updated any longer.

**Comment by tycho** [comment]
I'm not sure why you're chiming in to this issue @iSamF. I don't know what SAMTOOL is or why it is relevant.
